'use client';

import { useParams } from 'next/navigation';
import { useMemo, useState } from 'react';

type DocKind = 'grn' | 'gate_pass' | 'delivery_challan';

function label(kind: DocKind) {
  if (kind === 'grn') return 'Goods Receipt Note';
  if (kind === 'gate_pass') return 'Gate Pass';
  return 'Delivery Challan';
}

function number(kind: DocKind) {
  if (kind === 'grn') return 'GRN-PREVIEW-0001';
  if (kind === 'gate_pass') return 'GP-PREVIEW-0001';
  return 'DC-PREVIEW-0001';
}

export default function DocumentPrintPreviewPage() {
  const params = useParams<{ type: string }>();
  const kind = (params.type ?? 'gate_pass') as DocKind;
  const valid = ['grn', 'gate_pass', 'delivery_challan'].includes(kind);
  const [paper, setPaper] = useState<'a4' | 'a5'>(kind === 'grn' ? 'a4' : 'a5');

  const rows = useMemo(() => [
    {
      itemCode: 'PSY-MTR-03',
      itemName: 'Propulsion Motor CCW',
      qty: 2,
      uom: 'Nos',
      serialBatch: 'PSY-MTR-03-S0042, PSY-MTR-03-S0043',
      container: 'BN-014',
    },
  ], []);

  if (!valid) {
    return <main className="workflow-page"><section className="panel workflow-result error">Unknown document type.</section></main>;
  }

  return (
    <main className="print-document-shell">
      <div className="print-toolbar">
        <div>
          <strong>{label(kind)} Print Preview</strong>
          <div style={{ fontSize: 12, color: '#6c7890' }}>Preview data only · no ERP posting</div>
        </div>
        <div className="workflow-actions">
          <button className={paper === 'a5' ? 'scan-primary' : 'action'} type="button" onClick={() => setPaper('a5')}>A5</button>
          <button className={paper === 'a4' ? 'scan-primary' : 'action'} type="button" onClick={() => setPaper('a4')}>A4</button>
          <button className="scan-primary" type="button" onClick={() => window.print()}>Print</button>
        </div>
      </div>

      <section className={'print-paper ' + paper}>
        <div className="print-doc-header">
          <div>
            <h1>Hubblefly Technologies Limited</h1>
            <p>FacilityOS · {label(kind)}</p>
          </div>
          <div style={{ textAlign: 'right' }}>
            <strong>{number(kind)}</strong>
            <p>22 Sep 2026</p>
          </div>
        </div>

        <div className="print-doc-meta">
          {kind === 'grn' ? (
            <>
              <div><span>Supplier</span>Preview Supplier</div>
              <div><span>Supplier Invoice / Challan</span>INV-PREVIEW-001</div>
              <div><span>Warehouse</span>HFT Store</div>
              <div><span>Vehicle No.</span>HR-00-TEST</div>
            </>
          ) : (
            <>
              <div><span>Recipient / To</span>Preview Recipient</div>
              <div><span>Purpose</span>Material movement</div>
              <div><span>From</span>HFT Store</div>
              <div><span>Vehicle No.</span>HR-00-TEST</div>
              {kind === 'gate_pass' && <><div><span>Returnable</span>Yes</div><div><span>Expected Return</span>30 Sep 2026</div></>}
            </>
          )}
        </div>

        <table className="print-doc-table">
          <thead>
            <tr><th>#</th><th>Item Code</th><th>Description</th><th>Qty</th><th>UOM</th><th>Serial / Batch</th><th>Container</th></tr>
          </thead>
          <tbody>
            {rows.map((row, index) => (
              <tr key={row.itemCode}>
                <td>{index + 1}</td>
                <td>{row.itemCode}</td>
                <td>{row.itemName}</td>
                <td>{row.qty}</td>
                <td>{row.uom}</td>
                <td>{row.serialBatch}</td>
                <td>{row.container}</td>
              </tr>
            ))}
          </tbody>
        </table>

        <div style={{ marginTop: 12, fontSize: 9 }}>
          <strong>Remarks:</strong> Preview layout only. Final document will carry FacilityOS audit/reference data and applicable ERPNext document reference after reconciliation.
        </div>

        <div className="print-signatures">
          <div>Prepared By</div>
          <div>Checked By</div>
          <div>Authorized By</div>
        </div>

        <div style={{ marginTop: 20, paddingTop: 8, borderTop: '1px solid #111', fontSize: 8, textAlign: 'center' }}>
          Generated by Hubblefly FacilityOS · QR/reference block to be added in final print engine
        </div>
      </section>
    </main>
  );
}
