/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Int8 = ColumnType<string, bigint | number | string, bigint | number | string>;

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface CoreIdentifierAllocation {
  allocated_actor_id: string;
  allocated_actor_type: string;
  allocated_at: Timestamp;
  causation_id: string | null;
  command_id: string;
  correlation_id: string;
  id: string;
  identifier_value: string;
  legal_entity_id: string | null;
  organisation_id: string;
  period_key: string | null;
  period_token: string | null;
  request_id: string;
  sequence_id: string;
  sequence_value: Int8;
  series_id: string;
  site_id: string | null;
}

export interface CoreIdentifierSequence {
  created_at: Timestamp;
  id: string;
  legal_entity_id: string | null;
  next_value: Generated<Int8>;
  organisation_id: string;
  period_key: string | null;
  period_token: string | null;
  series_id: string;
  site_id: string | null;
  updated_actor_id: string;
  updated_actor_type: string;
  updated_at: Timestamp;
  version: Generated<Int8>;
}

export interface CoreIdentifierSeries {
  created_actor_id: string;
  created_actor_type: string;
  created_at: Timestamp;
  description: string | null;
  format_template: string;
  id: string;
  organisation_id: string;
  requires_period: Generated<boolean>;
  scope_legal_entity: Generated<boolean>;
  scope_site: Generated<boolean>;
  sequence_width: number;
  series_key: string;
  status: Generated<string>;
  updated_actor_id: string;
  updated_actor_type: string;
  updated_at: Timestamp;
  version: Generated<Int8>;
}

export interface CoreLegalEntity {
  code: string;
  country_code: string | null;
  created_actor_id: string;
  created_actor_type: string;
  created_at: Timestamp;
  display_name: string | null;
  id: string;
  legal_name: string;
  organisation_id: string;
  status: Generated<string>;
  updated_actor_id: string;
  updated_actor_type: string;
  updated_at: Timestamp;
  version: Generated<Int8>;
}

export interface CoreOrganisation {
  code: string;
  created_actor_id: string;
  created_actor_type: string;
  created_at: Timestamp;
  id: string;
  name: string;
  status: Generated<string>;
  updated_actor_id: string;
  updated_actor_type: string;
  updated_at: Timestamp;
  version: Generated<Int8>;
}

export interface CoreSite {
  code: string;
  created_actor_id: string;
  created_actor_type: string;
  created_at: Timestamp;
  id: string;
  name: string;
  organisation_id: string;
  status: Generated<string>;
  updated_actor_id: string;
  updated_actor_type: string;
  updated_at: Timestamp;
  version: Generated<Int8>;
}

export interface CoreSiteLegalEntity {
  created_actor_id: string;
  created_actor_type: string;
  created_at: Timestamp;
  id: string;
  legal_entity_id: string;
  organisation_id: string;
  site_id: string;
  status: Generated<string>;
  updated_actor_id: string;
  updated_actor_type: string;
  updated_at: Timestamp;
  version: Generated<Int8>;
}

export interface GovernanceApprovalDecision {
  approval_request_id: string;
  approver_user_id: string;
  capability_code: string;
  causation_id: string | null;
  command_id: string;
  correlation_id: string;
  decided_at: Timestamp;
  decision: string;
  id: string;
  legal_entity_id: string | null;
  organisation_id: string;
  reason: string | null;
  request_id: string;
  site_id: string | null;
}

export interface GovernanceApprovalRequest {
  causation_id: string | null;
  command_id: string;
  correlation_id: string;
  id: string;
  legal_entity_id: string | null;
  organisation_id: string;
  policy_code: string;
  request_capability_code: string;
  request_id: string;
  requested_action: string;
  requested_at: Timestamp;
  requester_user_id: string;
  require_distinct_humans: Generated<boolean>;
  required_approval_count: number;
  required_capability_codes: string[];
  resource_id: string;
  resource_type: string;
  self_approval_allowed: Generated<boolean>;
  site_id: string | null;
  status: Generated<string>;
  version: Generated<Int8>;
}

export interface GovernanceAuditEvent {
  action: string;
  actor_id: string;
  actor_type: string;
  authenticated_user_id: string | null;
  authorizing_capability: string | null;
  causation_id: string | null;
  command_id: string | null;
  correlation_id: string;
  creation_txid: string;
  event_type: string;
  event_version: number;
  id: string;
  legal_entity_id: string | null;
  metadata: Generated<Json>;
  occurred_at: Timestamp;
  organisation_id: string;
  outcome: string;
  reason: string | null;
  recorded_at: Timestamp;
  request_id: string;
  resource_id: string;
  resource_type: string;
  site_id: string | null;
  source_module: string;
}

export interface GovernanceHold {
  blocked_action: string | null;
  hold_type: string;
  id: string;
  legal_entity_id: string | null;
  organisation_id: string;
  placed_at: Timestamp;
  placed_by_user_id: string;
  placement_capability_code: string;
  placement_command_id: string;
  reason: string;
  release_approval_request_id: string | null;
  release_capability_code: string;
  release_reason: string | null;
  release_requires_approval: Generated<boolean>;
  released_at: Timestamp | null;
  released_by_user_id: string | null;
  resource_id: string;
  resource_type: string;
  site_id: string | null;
  status: Generated<string>;
  version: Generated<Int8>;
}

export interface GovernanceHoldAction {
  acted_at: Timestamp;
  action: string;
  actor_user_id: string;
  approval_request_id: string | null;
  causation_id: string | null;
  command_id: string;
  correlation_id: string;
  hold_id: string;
  id: string;
  legal_entity_id: string | null;
  organisation_id: string;
  reason: string;
  request_id: string;
  site_id: string | null;
}

export interface IamCapability {
  code: string;
  created_actor_id: string;
  created_actor_type: string;
  created_at: Timestamp;
  description: string | null;
  display_name: string;
  id: string;
  kind: Generated<string>;
  status: Generated<string>;
  updated_actor_id: string;
  updated_actor_type: string;
  updated_at: Timestamp;
  version: Generated<Int8>;
}

export interface IamRole {
  code: string;
  created_actor_id: string;
  created_actor_type: string;
  created_at: Timestamp;
  description: string | null;
  display_name: string;
  id: string;
  kind: Generated<string>;
  status: Generated<string>;
  updated_actor_id: string;
  updated_actor_type: string;
  updated_at: Timestamp;
  version: Generated<Int8>;
}

export interface IamRoleAssignment {
  created_actor_id: string;
  created_actor_type: string;
  created_at: Timestamp;
  id: string;
  legal_entity_id: string | null;
  organisation_id: string;
  role_id: string;
  scope_level: string;
  /**
   * A Site is physical scope only. Site-only assignments do not imply Legal Entity authority.
   */
  site_id: string | null;
  status: Generated<string>;
  updated_actor_id: string;
  updated_actor_type: string;
  updated_at: Timestamp;
  user_profile_id: string;
  valid_from: Timestamp;
  valid_until: Timestamp | null;
  version: Generated<Int8>;
}

export interface IamRoleCapability {
  capability_id: string;
  created_actor_id: string;
  created_actor_type: string;
  created_at: Timestamp;
  id: string;
  role_id: string;
  status: Generated<string>;
  updated_actor_id: string;
  updated_actor_type: string;
  updated_at: Timestamp;
  version: Generated<Int8>;
}

export interface IamUserProfile {
  /**
   * Immutable linkage to Supabase auth.users. Auth-user deletion is restricted to preserve operational identity/history.
   */
  auth_user_id: string;
  created_actor_id: string;
  created_actor_type: string;
  created_at: Timestamp;
  display_name: string;
  /**
   * Operational/display snapshot only. Supabase auth.users remains authentication email authority.
   */
  email_snapshot: string | null;
  id: string;
  status: Generated<string>;
  updated_actor_id: string;
  updated_actor_type: string;
  updated_at: Timestamp;
  version: Generated<Int8>;
}

export interface DB {
  "core.identifier_allocation": CoreIdentifierAllocation;
  "core.identifier_sequence": CoreIdentifierSequence;
  "core.identifier_series": CoreIdentifierSeries;
  "core.legal_entity": CoreLegalEntity;
  "core.organisation": CoreOrganisation;
  "core.site": CoreSite;
  "core.site_legal_entity": CoreSiteLegalEntity;
  "governance.approval_decision": GovernanceApprovalDecision;
  "governance.approval_request": GovernanceApprovalRequest;
  "governance.audit_event": GovernanceAuditEvent;
  "governance.hold": GovernanceHold;
  "governance.hold_action": GovernanceHoldAction;
  "iam.capability": IamCapability;
  "iam.role": IamRole;
  "iam.role_assignment": IamRoleAssignment;
  "iam.role_capability": IamRoleCapability;
  "iam.user_profile": IamUserProfile;
}
